### PR TITLE
Add support for Mares Sirius

### PR DESCRIPTION
**Pull request by rmultan**
Cherry pick changes from libdivecomputer to
allow support for Mares Sirius computer.

### CODE REVIEW

**Comment by mikeller** [comment]
What are the changeset id(s) that you cherry-picked from https://github.com/libdivecomputer/libdivecomputer for this?

**Comment by rmultan** [comment]
@mikeller  To be exact it's not a cherry pick anymore (as if git cherry pick), I just took code from libdivecomputer to make it work, because first time I did it I couldn't build Subsurface on my M1 Mac.  I made another attempt. I'm not familiar with C, so it was a bit of a struggle to fix merge issues, so I opted to pick manually what I needed.

Relevant commits from libdivecomputer https://github.com/libdivecomputer/libdivecomputer/compare/4516842a5aa3358e2b59fb3efbdc9990049bcb50...8fe598e1b098d457f595c5add02b71b98be30cef

**Comment by mikeller** [comment]
@rmultan: Unfortunately not having the original commits cleanly cherry-picked and the additional changes in a separate commit will create merge conflicts for all future merges from the libdivecomputer upstream. So merging this in its current form is not a good option.
I was planning to do an upstream merge from libdivecomputer in the near future anyway, so we can probably just wait until this will bring in the changes for the Mares Sirius.

**Comment by rmultan** [comment]
@mikeller Updated with an actual cherry pick. If it works for you I'm happy to update the version in the main repository as well, if not I'll just wait for your merge of the upstream.

**Review by mikeller — APPROVED** [review]
Looks good to me, thank you for contributing!

**Pull request merged**
