### PR TITLE
[RFC] Libdc updates

### PR DESCRIPTION
**Pull request by sfuchs79**
This is for the moment just a test of trying to learn how to help bringing libdc Subsurface-branch up to date.
I have to admit that my main interest is merging the OSTC 2 TR related update from Jeff to our Subsurface-branch.
Many open questions on my side:
- Is this a good idea at all if I try to do this or is it better when you (Dirk, Linus) do this only?
- Is it even ok to pick ALL the new stuff?
I had a quick look at the items and most of them looked reasonable to me. But I can image that there may be commits we don't want to have.
How could one cherry-pick commits while keeping the SHA and not destroying the git magic of being able to recognize the merged commits later-on?
- Did I fix the merge conflicts correctly? This for sure would need some review.
Side note: Compiling libdc gives so many warnings that it's not really easy for a beginner like me to quickly see if I may have messed s.th. up...

### CODE REVIEW

**Comment by dirkhh** [comment]
Because the merges tend to be painful, usually Linus takes care of them.

So my approach if I need libdc updated is to ping him. Therefore I'd suggest to ask him to take a look at your merge (or do his own that you could compare with)

And yes, the number of warnings bugs me. We need to fix that.

On March 11, 2018 6:13:11 AM PDT, Stefan Fuchs <notifications@github.com> wrote:
>This is for the moment just a test of trying to learn how to help
>bringing libdc Subsurface-branch up to date.
>I have to admit that my main interest is merging the OSTC 2 TR related
>update from Jeff to our Subsurface-branch.
>Many open questions on my side:
>- Is this a good idea at all if I try to do this or is it better when
>you (Dirk, Linus) do this only?
>- Is it even ok to pick ALL the new stuff?
>I had a quick look at the items and most of them looked reasonable to
>me. But I can image that there may be commits we don't want to have.
>How could one cherry-pick commits while keeping the SHA and not
>destroying the git magic of being able to recognize the merged commits
>later-on?
>- Did I fix the merge conflicts correctly? This for sure would need
>some review.
>Side note: Compiling libdc gives so many warnings that it's not really
>easy for a beginner like me to quickly see if I may have messed s.th.
>up...
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/Subsurface-divelog/libdc/pull/13
>
>-- Commit Summary --
>
>  * Cleanup the iterator internals
>  * Re-write the device discovery using the iterator api
>  * Add suport for applying a filter function
>  * Implement some filter functions
>  * Integrate the connect step into the open function
>  * Merge branch 'discovery'
>  * Suppress the warning if no O2 sensors are present
>  * Let the ringbuffer function handle a full ringbuffer
>  * Add a workaround for invalid logbook begin pointers
>  * Add support for the OSTC 2 TR
>  * Add functions for converting bluetooth addresses
>  * Add a high resolution timer module
>  * Use the new timer for the timeout calculations
>  * Use the new timer for the timestamps in the logging
>  * Handle the half-duplex emulation in the vyper2 backend
>  * Remove the half-duplex emulation from the I/O api
>  * Merge branch 'master' of libdivecomputer into Subsurface-branch
>
>-- File Changes --
>
>    M configure.ac (2)
>    M include/libdivecomputer/iostream.h (11)
>    M msvc/libdivecomputer.vcproj (8)
>    M src/Makefile.am (3)
>    M src/bluetooth.c (369)
>    M src/bluetooth.h (86)
>    M src/context.c (41)
>    M src/custom.c (13)
>    M src/custom.h (1)
>    A src/descriptor-private.h (44)
>    M src/descriptor.c (610)
>    M src/hw_ostc_parser.c (9)
>    M src/iostream-private.h (2)
>    M src/iostream.c (11)
>    M src/irda.c (273)
>    M src/irda.h (58)
>    M src/iterator-private.h (14)
>    M src/iterator.c (54)
>    M src/libdivecomputer.symbols (1)
>    M src/oceanic_common.c (40)
>    M src/platform.h (1)
>    M src/serial.h (32)
>    M src/serial_posix.c (251)
>    M src/serial_win32.c (205)
>    M src/shearwater_predator_parser.c (2)
>    M src/socket.c (6)
>    M src/socket.h (3)
>    M src/suunto_vyper2.c (57)
>    A src/timer.c (161)
>    A src/timer.h (51)
>    M src/usbhid.c (251)
>    M src/usbhid.h (43)
>    M src/uwatec_smart.c (65)
>
>-- Patch Links --
>
>https://github.com/Subsurface-divelog/libdc/pull/13.patch
>https://github.com/Subsurface-divelog/libdc/pull/13.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Subsurface-divelog/libdc/pull/13

-- 
from my phone.

**Comment by dirkhh** [comment]
On Sun, Mar 11, 2018 at 8:15 AM, Dirk Hohndel <dirk@hohndel.org> wrote:

> Because the merges tend to be painful, usually Linus takes care of them.
>

Ugh. And this one is worse than usual, because of the dc_descriptor_t
changes.

And no, Stefan's merge isn't correct - we've added the "serial"  field to
the dc_descriptor_t, and Jef now added that "filter" field, and now the
dc_descriptor_t needs to contain both.

Stefan just took Jef's version, which also means that the comments about
interface disappeared (ie the //FTDI etc comments that Dirk uses for
parsing).

That part is probably the right thing to do, though, it's too painful to
continue to maintain.

I'll try to take a look. I think we should probably try to get rid of our
"serial" field, just to avoid this horribly merge pain. That whole array
has always been a major painpoint for merging upstrea.,

                                       Linus

**Comment by sfuchs79** [comment]
Well, I feared s.th. like this. Thanks for having a look and taking care of this!

Just for me to learn s.th.:
Would there be a way to cherry-pick the one single commit for the "OSTC 2 TR" while at the same moment preserving it's SHA? I mean doing it in a way that git recognizes later-on that this commit is already merged when doing another merge for all the rest?

**Comment by torvalds** [comment]
[ Heh. I show up as "dirkhh" in the previous comment, because
apparently the email integration in the github comment system is a bit
odd. Whatever ]

On Sun, Mar 11, 2018 at 10:54 AM, Stefan Fuchs <notifications@github.com> wrote:
>
> Would there be a way to cherry-pick the one single commit for the "OSTC 2 TR" while at the same moment preserving it's SHA?

No - cherry-picking is very much like just applying a new patch. It
loses history, and it loses the connection with the original.

But we could do a cherry-pick just for the trivial OSTC 2 TR support,
no problem. That wouldn't cause much problems later.

But I think I'll just do the merge.

I probably *will* just drop the FTDI/USB/BLE comments, though, and
we'll have to maintain that some other way.

I'll also look at how painful it would be to get rid of the 'serial',
so that we wouldn't have this nasty bit difference to upstream going
forward.

                   Linus

**Comment by dirkhh** [comment]
Interesting. I wonder why you ended up being me... must be something about the reply address magic. Whatever.
I'm ok with dropping the FTDI/USB/BLE comments - @jefdriesen said he was going to replace this with something architectural that allows us to query this at run time, which is far less fragile than my hack.
Overall, of course, the closer we can reasonably be to libdivecomputer master, the easier the merges get - but I haven't even looked at the latest code (it may have been obvious but my last 6 weeks at work have been insanely busy and I'll get on another plane in two hours, so I'm struggling to even pretend to keep up...)
Thanks @torvalds

**Comment by torvalds** [comment]
It turns out that removing the 'serial' field is trivial, because nothing ever actually set it in the table in the first place. It was added so that it *could* be used, but it never was.

And I've gotten rid of the extra warnings, and the FTDI/USB/BLE comments, and am now just verifying that all. After that, I think the merge will be trivial.

**Comment by sfuchs79** [comment]
Closing this because @torvalds took over, see #14

**Comment by dirkhh** [comment]
Excellent, thanks.
Waiting for Stefan to test.
-- 
from my phone.

**Pull request closed without merging**
