### PR TITLE
Added detection and status messages for bailout to OC / switch back to CC for CCR dives.

### PR DESCRIPTION
**Pull request by mikeller**
This might need a bit of discussion.
As a CCR diver I would like to see the ability to properly track the 'on loop' / 'bailed out to open circuit' status directly in Subsurface, because this is an important (or even the most important) bit of status information during a CCR dive. This should extend to the use of the correct ppO2 / gas mix in the deco ceiling / tissue model calculation. My idea for how to do this would be to track the 'type' ('diluent' / 'OC bailout') for every gasmix / tank that is reported by the dive computer. Most CCR capable dive computers that I am familiar with require the user to enter two different gas lists for diluent and bailout, so this should work with the existing libdivecomputer API for these.
Unfortunately I think making this change in Subsurface will require a bit of work, as the libdivecomputer field capable of tracking the 'type' of a gas or tank (`cache->tankinfo[]`) does not seem to be consumed at all in Subsurface. So this pull request is just providing a prerequisite for the change in Subsurface by populating `tankinfo[]`. In addition to this it also triggers a message on every switch from CC to OC and back, at least giving a visual indication of these diver triggered events. The messages can probably be removed from libdivecomputer again once 'loop status' tracking has been added to Subsurface.

image

Also included is a fix of the tab expansion mess that I created in https://github.com/subsurface/libdc/pull/40. Apologies for this, I've switched to using a custom `.vimrc` for this project now.

Signed-off-by: Michael Keller <github@ike.ch>

### CODE REVIEW

**Comment by mikeller** [comment]
I hate to ask, but is it possible to get some traction on this one?
I am trying to improve CCR related gas logging for other dive computer models as well, and getting this (and #43) reviewed will help to clarify that the direction this is going is right.

**Comment by dirkhh** [comment]
I poked Linus - he doesn't always see GitHub notifications.

**Comment by torvalds** [comment]
Hmm. The commit message is a bit of a mess on that first commit, with overlong lines (that's a 702-character line!)

We had that earlier with the "Added parsing of the CCR setpoint information for Garmin Descent computers." that I merged as part of "added_garmin_ccr_setpoint_info", and I dread getting more of these.

But the changes look sane per se.

**Comment by mikeller** [comment]
Apologies, I am new to the approach to add a detailed description of the changes to the commit message, instead of adding it to the pull request, and did not take care to rewrap my commit messages after editing. Fixed now.

**Comment by torvalds** [comment]
Cherry-picked the one remainming commit in the updated pull.

**Pull request closed without merging**
